version: 2
jobs:
  build:
    machine: true
    environment:
      APPLICATION_LOG_PATH: /app
      TIME_KEY: time
      TAG_PREFIX: app
      AGGREGATOR_HOST: 127.0.0.1
    steps:
      - checkout
      - run:
          name: build
          command: |
            docker build -t fluentd-forward:latest .
      - run:
          name: Config check
          command: |
            docker run --rm -v $(pwd):/fluentd/etc/ -e APPLICATION_LOG_PATH=$APPLICATION_LOG_PATH -e TIME_KEY=$TIME_EKY -e TAG_PREFIX=$TAG_PREFIX -e AGGREGATOR_HOST=$AGGREGATOR_HOST fluentd-forward:latest fluentd --dry-run -c /fluentd/etc/fluent.conf -v
